repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11.5
        stages: [commit]
  - repo: local 
    hooks:
        - id: pytest
          name: pytest
          language: system
          always_run: true
          entry: pytest -v -s
          pass_filenames: false
          stages: [commit]